library(conflicted)
library(tidyverse)
t <- read.csv("ACLED.csv")
f_by_e <- t |> group_by(event_type) |> summarize(sum(fatalities))
nb_f <- sum(t$fatalities)
stopifnot(nb_f == sum(f_by_e[2]))
f_by_i <- t |> group_by(interaction) |> summarize(sum(fatalities))
